services:
  backend:
    image: ${NODE_IMAGE}
    working_dir: /app
    command: yarn serve
    volumes:
      - ../backend:/app

  nginx:
    image: ${NGINX_IMAGE}
    ports:
      - 80:80
    volumes:
      - ../nginx/templates.ci:/etc/nginx/templates
      - ../frontend/dist:/var/www
    depends_on:
      - backend
