version: '3'

dotenv: [.env]

tasks:
  env:
    desc: makes .env from .env.example
    cmds:
      - cp .env.example .env
      - cp .env.example ../.env.production.local

  init:
    desc: pulls all docker images
    cmds:
      - docker pull $PLAYWRIGHT_IMAGE
      - docker pull $NODE_IMAGE
      - task yarn

  yarn:
    cmds:
      - |
        docker run \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE yarn

  up:
    desc: start services
    cmds:
      - docker compose up -d

  down:
    desc: stops services
    cmds:
      - docker compose down

  bash:
    cmds:
      - |
        docker run \
          -it --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash

  lint:
    cmds:
      - |
        docker run \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash -c "yarn lint"

  build:
    cmds:
      - |
        docker run \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash -c "{{.CLI_ARGS }} yarn build"

  test:
    cmds:
      - task test:unit
      - task test:e2e

  test:e2e:
    cmds:
      - |
        docker run \
          --rm --network="host" \
          -v $(pwd)/..:/app \
          -w /app \
          $PLAYWRIGHT_IMAGE \
          yarn test:e2e

  test:unit:
    cmds:
      - |
        docker run \
          -v $(pwd)/..:/app \
          -w /app \
          $NODE_IMAGE \
          yarn test:unit
