version: '3'

dotenv: [.env]

tasks:
  env:
    cmds:
      - cp .env.example .env
      - cp .env.example ../.env.development.local

  init:
    cmds:
      - task yarn
      - docker pull $PLAYWRIGHT_IMAGE
      - docker build -t vitest-ui - < ./VitestUi.Dockerfile --build-arg NODE_IMAGE

  up:
    desc: start services
    cmds:
      - docker compose up -d

  down:
    desc: stops services
    cmds:
      - docker compose down

  restart:
    desc: restart services
    cmds:
      - task down
      - task up

  logs:
    desc: logs the development compose
    cmds:
      - docker compose logs -f

  bash:
    cmds:
      - |
        docker run --user $USERID \
          -it --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash

  yarn:
    desc: You can pass additional parameters like 'task yarn -- add -D vue', which will be resulted in 'yarn add -D vue'
    cmds:
      - |
        docker run --user $USERID \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash -c "yarn {{.CLI_ARGS }}"

  lint:
    cmds:
      - |
        docker run --user $USERID \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash -c "yarn lint"

  lint:fix:
    cmds:
      - |
        docker run --user $USERID \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash -c "yarn lint:fix"

  build:
    cmds:
      - |
        docker run --user $USERID \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash -c "yarn build"

  test:e2e:ui:
    desc: runs Playwright in UI mode (works only in Linux)
    # TODO: Please refer to https://www.oddbird.net/2022/11/30/headed-playwright-in-docker/ if you want to make it work on Windows or macOS
    cmds:
      - |
        docker run --user $USERID \
          --rm --network="host" --ipc=host \
          -e DISPLAY=${DISPLAY} \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -v $(pwd)/..:/app \
          -w /app \
          $PLAYWRIGHT_IMAGE \
          yarn test:e2e:ui
